# Site Settings
title: Peter Fox Flick
author: Peter Flickinger
description: > # this means to ignore newlines until "twitter_username:"
  This is my project show off site. Here I show my projects built with Aruduinos,
  Google Script, Trello API, or other programs and fun things that I have done.

baseurl: "/"
url: "http://peterfoxflick.github.io"


# social links
github_username:  peterfoxflick
# tagline: "Here we go"

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

markdown: kramdown

show_excerpts: true # set to true to show excerpts on the homepage

google_analytics: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
